In [ ]:
from torchvision import transforms
from torchvision import datasets
import torch
from PIL import Image

In [ ]:
torch.version

<module 'torch.version' from '/usr/local/lib/python3.7/dist-packages/torch/version.py'>

In [ ]:
myNN = torch.hub.load('pytorch/vision:v0.10.0', 'alexnet', pretrained=True)
myNN.eval()

Using cache found in /root/.cache/torch/hub/pytorch_vision_v0.10.0


AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [ ]:
input_image = Image.open("./input.jpg")

preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
input_transformed = preprocess(input_image)
print(input_transformed.size())


torch.Size([3, 224, 224])


In [ ]:
#substitute the last layer
#probably saving wont work
#copy needed
originalLastLayer = myNN.classifier._modules['6']
originalLastLayer


Linear(in_features=4096, out_features=1000, bias=True)

In [ ]:
myNN

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [ ]:
for param in myNN.parameters():
    param.requires_grad = False

# Freezing params

In [ ]:
myNewLayer = torch.nn.Linear(in_features=4096, out_features=6, bias=True)


myNN.classifier =  torch.nn.Sequential(*list(myNN.classifier.children())[:-1])
#myNN.classfier._modules['6'] = myNewLayer
myNN


AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [ ]:
myNN.classifier._modules['6'] = myNewLayer
myNN

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [ ]:
myNN.classifier._modules['7'] = torch.nn.Softmax(dim=1)

In [ ]:
myNN


AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [ ]:
torch.unsqueeze(input_transformed, 0).shape

torch.Size([1, 3, 224, 224])

In [ ]:
myNN(torch.unsqueeze(input_transformed, 0))

tensor([[0.1719, 0.0368, 0.2967, 0.0961, 0.1631, 0.2353]],
       grad_fn=<SoftmaxBackward0>)

In [ ]:
torch.sum(myNN(torch.unsqueeze(input_transformed, 0)))

tensor(1.0000, grad_fn=<SumBackward0>)

In [ ]:
#TODO freeze the old net, train new layer with cross entropy loss, what is gcp???
#kaggle -> it has nice online machine
#NEEDED: read data with dataloader
#To try: add GPU
#jain = ja + nein
#AWS sagemaker
#Do not mix pandas/numpy with GPU solutions -> causes movement of data
#Add confusion matrix

In [ ]:
DATAPATH = "./drive/MyDrive/CNN/flowers/flowers/flower_photos/"

In [ ]:
originalLastLayer

Linear(in_features=4096, out_features=1000, bias=True)

In [ ]:
train_ds = datasets.ImageFolder(DATAPATH+"train", transform=preprocess)
print(train_ds[0])
train_dl = torch.utils.data.DataLoader(train_ds, batch_size=10, shuffle=True)
print(train_dl)


(tensor([[[0.8789, 0.8104, 0.7419,  ..., 0.6563, 0.6734, 0.6906],
         [0.8961, 0.8618, 0.8104,  ..., 0.6734, 0.7077, 0.7248],
         [0.9646, 0.9303, 0.8961,  ..., 0.7077, 0.7419, 0.7419],
         ...,
         [0.4166, 0.3994, 0.3823,  ..., 0.3481, 0.3823, 0.3652],
         [0.3994, 0.3823, 0.3823,  ..., 0.3309, 0.3481, 0.3481],
         [0.3652, 0.3652, 0.3823,  ..., 0.3309, 0.3138, 0.3309]],

        [[1.0280, 0.9580, 0.8880,  ..., 0.8004, 0.8179, 0.8354],
         [1.0455, 1.0105, 0.9755,  ..., 0.8179, 0.8529, 0.8704],
         [1.1155, 1.0805, 1.0630,  ..., 0.8529, 0.8880, 0.8880],
         ...,
         [0.5378, 0.5203, 0.5028,  ..., 0.5028, 0.5378, 0.5203],
         [0.5203, 0.5028, 0.5028,  ..., 0.4853, 0.5028, 0.5028],
         [0.4853, 0.4853, 0.5028,  ..., 0.4853, 0.4678, 0.4853]],

        [[1.3851, 1.3154, 1.2282,  ..., 1.0191, 1.0365, 1.0539],
         [1.4025, 1.3677, 1.3154,  ..., 1.0365, 1.0714, 1.0888],
         [1.4722, 1.4374, 1.4025,  ..., 1.0714, 1.1062, 1

In [ ]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(myNN.parameters(), lr=0.001, momentum=0.9)

In [ ]:
numEpochs = 1

In [ ]:
for epoch in range(numEpochs):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(train_dl, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = myNN(inputs)
        #print(labels)
        #print(outputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 20 == 19:    # print every 20 mini-batches
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
            running_loss = 0.0

print('Finished Training')


[1,    20] loss: 0.013
[1,    40] loss: 0.013
[1,    60] loss: 0.012
[1,    80] loss: 0.012
[1,   100] loss: 0.012
[1,   120] loss: 0.012
[1,   140] loss: 0.012
[1,   160] loss: 0.012
[1,   180] loss: 0.012
[1,   200] loss: 0.012
[1,   220] loss: 0.012
[1,   240] loss: 0.012
[1,   260] loss: 0.012
[1,   280] loss: 0.012
[1,   300] loss: 0.012
[1,   320] loss: 0.012
[1,   340] loss: 0.012
Finished Training


In [ ]:
#add accuracy, test set, confusion matrix

In [ ]:
test_ds = datasets.ImageFolder(DATAPATH+"test", transform=preprocess)

test_dl = torch.utils.data.DataLoader(test_ds, batch_size=10, shuffle=True)



In [ ]:
import numpy as np
confussion = np.zeros((5,5))

# iterate over test data
for inputs, labels in test_dl:
    output = myNN(inputs) # Feed Networ        
    for i, pred in enumerate(output):
        #print(labels[i])
        #print(torch.argmax(output[i]))
        confussion[labels[i]][torch.argmax(output[i])] +=1

print(confussion)

[[9. 0. 1. 0. 0.]
 [0. 9. 0. 0. 1.]
 [0. 1. 6. 0. 3.]
 [1. 0. 0. 9. 0.]
 [2. 0. 1. 0. 7.]]


In [ ]:
import matplotlib.pyplot as plt
plt.matshow(confussion)